[Definition]

actionban = /bin/bash /home/usuario/sistema_seguridad/enviar_telegram.sh "🚫 FAIL2BAN: IP <ip> bloqueada por <name> en el servidor de seguridad."

actionunban = /bin/bash /home/usuario/sistema_seguridad/enviar_telegram.sh "🚫 FAIL2BAN: IP <ip> desbloqueada en <name>."
